spring:
  application:
    name: wallet-service
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://wallet-db:5432/wallet-db?createDatabaseIfNotExist=true
    username: postgres
    password: wallet123
    driver-class-name: org.postgresql.Driver

rabbit-mq-props:
  host: rabbit-mq
  durable: true
  exclusive: false
  auto-delete: false
  to-pup-queue: wallet.queue.top-up
  credit-queue: wallet.queue.credit
  debit-queue: wallet.queue.debit
  wallet-create-queue: wallet.queue.create
  exchange: wallet-exchange
  top-up-key: wallet.top-up
  credit-key: wallet.credit
  debit-key: wallet.debit
  wallet-create-key: wallet.create

server:
  port: 9994

logging:
  level:
    root: info
    com.rabbitmq: info
    com.mariesto.walletservice: info

management:
  health:
    rabbit:
      enabled: true