server:
  port: 9991


spring:
  application:
    name: payment-service
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://payment-db:5432/payment-db?createDatabaseIfNotExist=true
    username: postgres
    password: payment123
    driver-class-name: org.postgresql.Driver

rabbit-mq-props:
  host: rabbit-mq
  durable: true
  exclusive: false
  auto-delete: false
  exchange: wallet-exchange
  top-up-key: wallet.top-up
  credit-key: wallet.credit
  debit-key: wallet.debit

logging:
  level:
    com.rabbitmq: info
    com.mariesto.paymentservice: info
    root: info

management:
  health:
    rabbit:
      enabled: true