spring:
  application:
    name: user-service
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://user-db:5432/user-db?createDatabaseIfNotExist=true
    username: postgres
    password: user123
    driver-class-name: org.postgresql.Driver


server:
  port: 9992

